version: '3.7'
services:
    webserver:
        build:
            context: ./web
        image: ntt-live-nginx
        volumes:
            - ${PWD}/web/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80
        networks:
            - app-front
        depends_on:
            - app

    app:
        build:
            context: ./app
            dockerfile: Dockerfile.multi
        image: app
        environment:
            - DBSERVER=db
            - DATABASE=pokemon
            - COLLECTION=pokemon
        networks:
            - app-front
            - app-back
        depends_on:
            - db

    db:
        image: mongo
        networks:
            - app-back

networks:
    app-front:
        name: app-front

    app-back:
        name: app-back